### ISSUE TITLE
One or more Mageplaza extensions are not validated...

### ISSUE THREAD

**Issue by COTIGA** [mageplaza/module-core#12]
Hello,
I have this message display:
`One or more Mageplaza extensions are not validated. Click here to validate them.
`
and do not know how to make it disappear.
Thank you for helping me.

M2 v2.2.3
mageplaza/module-smtp v1.0

**Comment by haitv282** [comment]
Hi @COTIGA ,

Thanks for using our extension.
You can go to `Mageplaza > SMTP > Configuration > Module Information`
Next fill required information and click **Activate**

**Comment by COTIGA** [comment]
Sorry, but I can not get rid of this message.
I uninstalled and reinstalled the module, did what it takes ..., but after clearing the cache (as requested by Magento) the message comes back.
Maybe because I do not choose a predefined Provider, mine is OVH (I did a pull-request for you to add it). So I leave the "SMTP Provider" field empty and fill in the rest of the form.
My mails are well shipped, the only problem encountered is this persistent message.

**Comment by haitv282** [comment]
Hi @COTIGA 
Please upgrade the Core module to the latest version 1.3.10 to solve this issue.

**Comment by max-hung** [comment]
Hello
I upgraded mageplaza/module-core to 1.3.10,but this message still it.
and not found Mageplaza > SMTP > Configuration > Module Information
Next fill required information and click Activate

**Comment by spectravp** [comment]
I have the same issue. Core is version 1.3.11 and the message persists. 

There is no section "Module Information" in the admin.   (SMTP config information removed from image for security)
<img width="1206" alt="screen shot 2018-03-28 at 11 10 18 am" src="https://user-images.githubusercontent.com/272688/38038300-a6e91bec-3278-11e8-8a42-6ee9a097e8b9.png">

**Comment by BhaskarPothineni** [comment]
Mageplaza smtp module is not working magento 2.1.15 .
It is not showing SMTP configuration information and throwing the warning message like one or more mageplaza extensions are not validated. When ever click on that it is not showing anything.
