### ISSUE TITLE
main.CRITICAL: Warning:  on Mageplaza/Search

### ISSUE THREAD

**Issue by vivekaris** [mageplaza/module-core#14]
main.CRITICAL: Warning: Invalid argument supplied for foreach() in app/code/Mageplaza/Search/Helper/Data.php on line 345

**Comment by gixid192** [comment]
@vivekaris this is Core module, what you are asking is Search module.
Kindly create a new ticket here, we support you via ticket system https://mageplaza.freshdesk.com/helpdesk/tickets

For now, we will close the issue here.
