### ISSUE TITLE
Mageplaza_LayeredNavigation: Search is NOT idempotent (different responses for identical requests)

### ISSUE THREAD

**Issue by AlexeyFreelancer** [mageplaza/module-core#15]
Search should be idempotent and return always the same response for identical requests (of course, without cache and if data in db were not changed).

**Steps to reproduce**
 - go to category view page
 - remember sorting of products
 - open the same page but without cache (just add random GET param to url, e.g. ?rand=randomvalue)
 - compare with previous result

**Actual result**
Sorting is different

**Expected result**
Sorting should be the same even with disabled cache

**Solution**
Add the following code to the file \Mageplaza\LayeredNavigation\Model\ResourceModel\Fulltext\Collection
 ```
    /**
     * @inheritdoc
     */
    protected function _beforeLoad()
    {
        /*
         * This order is required to force search results be the same
         * for the same requests and products with the same relevance
         * NOTE: this does not replace existing orders but ADDs one more
         */
        $this->setOrder('entity_id');
        return parent::_beforeLoad();
    }
```

**Resources**
 - The same issue for magento search: https://github.com/magento/magento2/issues/12860#issuecomment-362446400
 - Fixed in v2.2.4: https://github.com/magento/magento2/blob/2.2/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php#L375

**Comment by gixid192** [comment]
Thanks for your report. We will check and fix the issue soon.
