### ISSUE TITLE
What's the purpose of the core module in M2 front-end

### ISSUE THREAD

**Issue by robhuijben** [mageplaza/module-core#21]
I was wondering what the purpose of module core is for the Magento 2 front-end. When installed, the core modules loads a lot of view files which in my opinion are useless for a core module. Also some modules as Owl Carousel are added to the JS bundle.

Can someone explain to me why this happens?

**Comment by gixid192** [comment]
This core module provides files and functions that needed for all of our extensions.
If you don't use Mageplaza's modules, you should not download this core module.

**Comment by peterjaap** [comment]
But then you should remove the dependency by your SMTP extension on the core, since that extension requires the core and the core will add frontend stuff the SMTP extension doesn't need.

Using a core module to depend your modules on is considerend bad practice according to the [Extension Development Network](https://extdn.org).

**Comment by oviliz** [comment]
Indeed, I don't see any reason to having https://github.com/mageplaza/module-core/blob/master/view/base/web/js/owl.carousel.min.js bundled when only the SMTP module is used.
```
./pub/static/adminhtml/Magento/backend/en_US/js/bundle/bundle6.js:2:
./pub/static/frontend/TfT/tft/en_US/js/bundle/bundle3.js:2:
./pub/static/frontend/Magento/luma/en_US/js/bundle/bundle3.js:2:
```
Any chance this can be reviewed @gixid192 as recommended first by @peterjaap ?

**Comment by robhuijben** [comment]
I hope @gixid192 consider opening this topic again and move the unneeded files to another package as a dependency for module that _do_ need these.
