### ISSUE TITLE
Can not disable adding tips from Mageplaza in admin panel

### ISSUE THREAD

**Issue by oleksandr-butenko** [mageplaza/module-core#22]
After we updated to 1.4.0 we  got links in different places that we can't disable. 
It looks like flag "store_helper" in /etc/adminhtml/system.xml is not used anywhere. 

Please fix it.

**Comment by gixid192** [comment]
We disabled the function, kindly pull the latest code to fix the issue.
Thank you.

**Comment by gixid192** [comment]
Thanks for your suggestion. We already implemented it in the default.xml file.
If you have a further concern or advise, kindly let us know here, otherwise, please help me close this issue.

Thank you.

**Comment by oleksandr-butenko** [comment]
OK. it's commented. I assume you will finalize that later. 
Closing the issue.
