### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by travis-shippingtree** [mageplaza/module-core#25]
I've tried the #2 method of installation multiple times on fresh installs, and it doesn't work. 

I start a fresh install using the bitnami-magento-2.1.7-0-linux-ubuntu-14.04-x86_64-hvm-ebs (ami-76b2e760) AMI from AWS, have to change some file permissions, and the two commands seem to work:

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

setup:upgrade recommends I re-compile, so I also do a: 

php bin/magento setup:di:compile 

Refresh the admin page and the extensions tab does not show up on the left side.

**Comment by gixid192** [comment]
I need to clarify 1 thing: I worked with Bitmap before and it was weird. Sometimes, you need to check a specific settings/cache to make it work
So my advise is to make sure that your server is up and running normally before you install any third party module.

For the troubleshoot:
You can check the module status by running: php bin/magento module:status. See if the Mageplaza_Core is listed and NOT in the Disabled module section.

**Comment by travis-shippingtree** [comment]
Thanks for the tip. I did confirm this each time but changing the admin login and logging into make sure things were working properly. 

I'll try by starting up a fresh install by manually installing mysql, apache, php, etc. and see how that goes.

Thanks!

**Comment by gixid192** [comment]
Let us know if you still have the issue.
This issue will be closed after 7 days if you don't response. Please feel free to open it if you have any further questions.
