### ISSUE TITLE
Install through composer doesn't work

### ISSUE THREAD

**Issue by travis-shippingtree** [mageplaza/module-core#27]
Magento 2.2.8
Ubuntu
Apache 2.4

Fails with error:

`Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
`

```
$ composer require mageplaza/module-core
Cannot create cache directory /home/magento/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/magento/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/magento/.composer/cache/files/, or directory is not writable. Proceeding without cache

    Authentication required (repo.magento.com):
      Username: XXXXX
      Password:
Do you want to store credentials for repo.magento.com in /home/magento/.composer/auth.json ? [Yn] Y
Using version ^1.4 for mageplaza/module-core
./composer.json has been updated
Cannot create cache directory /home/magento/.composer/cache/repo/https---repo.magento.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/magento/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/magento/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mageplaza/module-core (1.4.3): Downloading (100%)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

```

**Comment by gixid192** [comment]
Did you check the module status? Is it running now?

**Comment by gixid192** [comment]
I just realized that you already created an issue here: https://github.com/mageplaza/module-core/issues/25
To help trace the issue easier, kindly go over that issue and continue the conversation.

Thank you.

**Comment by travis-shippingtree** [comment]
They are separate issues. 
#25 is for the copy + paste method
#27 is for the composer method

**Comment by gixid192** [comment]
I see the "#2" in your first message so I thought it's composer. Sorry for my mistake.

For the current issue, kindly confirm my question above. How is the status of Mageplaza_Core now?

**Comment by travis-shippingtree** [comment]
Hi Jimmy,

No problem. I was able to install it with the #2 method on an installation I created on Ubuntu with Apache 2.4/PHP 7.2. 

For what it's worth, the installation of Magento went much smoother on Ubuntu - there were a large number of problems on Amazon's Linux OS. This guide was straight forward and easy to follow:

https://www.linode.com/docs/websites/ecommerce/install-magento-on-ubuntu-18-04/

That said, #25 can probably be closed, because of the oddity of the bitnami AMI I was using, I think that it's an issue unique to that AMI. 

However, the composer install doesn't work on a good clean Magento 2.2 install on Ubuntu.

Hope this helps! Thank you.

**Comment by gixid192** [comment]
Composer will check all the dependences, not only the module-core or any module you will install so I guess you can't install any other modules due to that error.

To be honest, I never try it myself, whenever I see a report like this, I advise the customer to switch to copy/paste method. Please help me check the following points:
- Your php version is compatible, it's silly as your Magento 2.2 is up and running but running php -v don't take much time
- Here they said it will still install, you can just ignore the message https://digitalstartup.co.uk/t/magento-2-3-composer-install-error/393
- You can try the Setup Wizard provided by Magento: https://imgur.com/rnFXupj

Please let me know if it work for you.

**Comment by gixid192** [comment]
Close as no response within 7 days.
