### ISSUE TITLE
Error. Refused to apply style from... because its MIME type ('inode/x-empty') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by volanar** [mageplaza/module-core#28]
Hello. I get this error in console google chrome:
Refused to apply style from 'https://domen.com/pub/static/version1557922565/frontend/Mgs/claue/ru_RU/Mageplaza_Core/css/magnific-popup.css' because its MIME type ('inode/x-empty') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by gixid192** [comment]
Could you check the permission of the pub folder? And try deploying with the ru_RU language?
The systax will look something like this: `bin/magento setup:static-content:deploy ru_RU`
Please let us know the status of the issue. Thank you.

**Comment by gixid192** [comment]
Close as no response. Feel free to re-open if you still have the issue.

**Comment by wilhelmpa** [comment]
same here....
