### ISSUE TITLE
Error when building Magento 2

### ISSUE THREAD

**Issue by jfgalano** [mageplaza/module-core#30]
Magento version 2.2.8
1) composer update OK
2) build of Magento 2
3) Error when trying to download Mageplaza/module-core

W: - Installing mageplaza/module-core (1.4.4): Downloading 
W: 
W: [Composer\Downloader\TransportException] 
W: The 'https://repo.magento.com/archives/mageplaza/module-core/mageplaza-module-core-1.4.4.0.zip' URL could not be accessed: HTTP/1.1 403 Forbidden

**Comment by LuongNgoDoan** [comment]
Hi!
We tried to install module core in Magento 2.2.8 via composer with the command line below:
composer require mageplaza/module-core
It succeeded, and we did not encounter any issue. Can you please clarify your problem in more details? It should be better if you can explain in steps by steps to replicate your issue

**Comment by gixid192** [comment]
Close due to no response within 7 days.
Feel free to comment if you have further related issues.
