### ISSUE TITLE
XS Vulnerability

### ISSUE THREAD

**Issue by sangthieu** [mageplaza/module-core#31]
Hi We found issue when we debug error "XS Vulnerability - Failed." in magento secure scan.

That error gone after disable module mageplaze core. Can you check and update module.

XS Vulnerability - Failed.
XSS Patch not detected (APPSEC-2143), response body contains unexpected '<script>alert("hello");</script>'

**Comment by gixid192** [comment]
Thanks for your report.

We would like to see the full report, does it tell you what file that cause the issue?
To be clear, our Core module only works as a base module, it does not render anything so I really help you can provide us more information about the issue.

**Comment by sangthieu** [comment]
@gixid192 I found issue. problem is module Mageplaza_SeoPro. When i disable module core, module SEO pro disabled.

In file Mageplaza\SeoPro\Plugin\SeoProRender.php

Somehow hacker can attach the canonical link

if ($this->helperConfig->isEnableCanonicalUrl()
            && !in_array($this->request->getFullActionName(), $this->helperConfig->getDisableCanonicalPages())
            && !$this->checkRobotNoIndex()
        ) {
            // $this->pageConfig->addRemotePageAsset(
            //     $this->url->getCurrentUrl(),
            //     'canonical',
            //     ['attributes' => ['rel' => 'canonical']]
            // );
        }

**Comment by gixid192** [comment]
Thanks for your code.
I'm trying to understand the situation here, I hope you can help me with your knowledge.

You said `Somehow hacker can attach the canonical link`, I'm trying to make clear of this sentence, in which case and how a person can add a link to your store? Is your store a blog that allows guest posts?
With my little experience in SEO, I think a canonical link is something that only store owner can add (as only store owner has the permission to edit the content of the store/shop/web)

**Comment by gixid192** [comment]
I will close the issue from here. Feel free to reopen the issue if you have further reports.

**Comment by umitengiz** [comment]
I have faced the same issue on Magento 2.2.5. Magento Security Scanner was suggesting me to upgrade Magento to 2.2.7 and i did but nothing changed. The exact problem is on **Mageplaza_SeoPro**. You can find the fail statement and description on the attachment.

![xsvul](https://user-images.githubusercontent.com/10435899/61600990-21682780-ac3c-11e9-8cde-9b831bd841f4.PNG)

It is ok after disabling **Mageplaza_SeoPro** which i have ultimate version of the extension.

**Comment by gixid192** [comment]
Hi @umitengiz, thanks for your information, now I know it's Magento Security Scanner.
I tried and received the same report as you guys reported.

To be honest, I have no idea where it comes from. I go ahead and tried other Scanner, which is also very popular: https://www.magereport.com/scan/?s=http://seoultimate.demo.mageplaza.com/

It doesn't say anything about the XSS or Magento 2 problems.

@umitengiz Could you tell me how you `disable` the extension? Did you disable it in the configuration, from command line or from the config.php file?

**Comment by umitengiz** [comment]
From config.php, making it zero and bin/magento setup:upgrade.

**Comment by sangthieu** [comment]
@umitengiz that is what i debug module Mageplaza_SeoPro. Then i try remove some line in SeoPro/etc/frontend/di.xml.

<type name="Magento\Framework\View\Page\Config\Renderer">
        <plugin name="SeoProRender" type="Mageplaza\SeoPro\Plugin\SeoProRender"/>
    </type>

**Comment by gixid192** [comment]
Thank guys!
I re-opened this issue, checking the problems you guys report. Will get back when I have updates on this.

**Comment by gixid192** [comment]
So I followed your guide:
- Disable the SeoPro extension
- Edit this file: SeoProRender.php
![SeoProRender](https://i.imgur.com/c9HM0Re.png)

As you can see, I changed the function to a string. And the problem disappear.
So it is the same as @sangthieu result, and my explanation is still the same. That code responses for the canical link and it's something that from client-side, users cannot control.

I'm thinking of putting a check on that line (see if it's actually a URI) but if it's for internal usage, this check won't be needed.
Please let me know your opinions about this.

**Comment by gixid192** [comment]
Hi,

I just changed the code to strip all tags in the Url. It's working well with Magento Scanner.
`trim(strip_tags($this->url->getCurrentUrl()))`

**Comment by sangthieu** [comment]
Hi @gixid192 ,
trim and strip_tags working for me.
Thanks

**Comment by gixid192** [comment]
Thanks for your feedback.
As the issue came from Seo extension and it is also resolved, I will close the issue from here.

For the update, we will push the code to update Seo extensions soon.
