### ISSUE TITLE
[Resolved] Specified invalid parent id (Mageplaza_Core::menu)

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/module-core#6]
## Problem

After install I got this message in backend.

It is because of old Mageplaza Core module.
You have to upgrade to higher version. From **Mageplaza_Core v1.3.0** it was added Menu.

## Solution

Access to your website via command line. Run the following command line on Magento 2 root directory:

```
composer update mageplaza/module-core
php bin/magento setup:upgrade
```

Q: I got this issue: `Mageplaza_Core has been already defined`
A: Read this guide: #3

**Comment by fabianearaujo** [comment]
Estou com o mesmo problema, mas para mim não resolveu com esse comando.

**Comment by MunteanuRoman** [comment]
Hello, 

We bought the GMT module from you which requires the Core extension but though we tried everything in the end we get the same result:

> a:4:{i:0;s:50:"Specified invalid parent id (Mageplaza_Core::menu)";i:1;s:5933:"#0 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Backend\Model\Menu\Builder->getResult(Object(Magento\Backend\Model\Menu))

The suggested actions didn't help. Is there anything we can do?

**Comment by 100rabhMisra** [comment]
I have faces same issue Specified invalid parent id (Mageplaza_Core::menu) to [Resolved] Specified invalid parent id (Mageplaza_Core::menu) please suggest me what i do  ?

**Comment by haitv282** [comment]
Hi @100rabhMisra 
Please upgrade this Core module to solve this problem. 
```
composer update mageplaza/module-core
php bin/magento setup:upgrade
```
If you cannot run composer, you can download module code from github and put it to: `app/code/Mageplaza/Core`. Then run `upgrade` command to install it.

Thank you very much.

**Comment by arroyo** [comment]
Thank you, this was helpful.  We ran into it on our staging server.
