### ISSUE TITLE
Missing Zend Library in Magento 2.4.6

### ISSUE THREAD

**Issue by Sharkozp** [mageplaza/module-core#63]
Hello,

I am testing Magento 2.4.6-beta2 and found that yours module Mageplaza/Core is using Zend Library that is missing in new version of Magento, for ex. here
https://github.com/mageplaza/module-core/blob/master/Model/Activate.php:73-79

`$curl->write(
            Zend_Http_Client::POST,
            self::MAGEPLAZA_ACTIVE_URL,
            '1.1',
            [],
            http_build_query($params)
        );`

**\Zend_Http_Client::POST** can be replaced with **\Laminas\Http\Request::METHOD_POST**

but this https://github.com/mageplaza/module-core/blob/master/Model/Activate.php:86
`$responseBody = Zend_Http_Response::extractBody($resultCurl);`
I can't find replacement in Laminas and it must be refactored

Best wishes

**Comment by micheledalonzo** [comment]
Hi, any update on this issue?

**Comment by miller75** [comment]
Same issue here

**Comment by andrewsurrey** [comment]
bump.

**Comment by Mario12335** [comment]
Try this for now until they fix:
`composer require magento/zendframework1`
Solution found here:
https://magento.stackexchange.com/a/365565

**Comment by miller75** [comment]
Replace Mageplaza/Core/Model/Activate.php with the following

`<?php
/**
 * Mageplaza
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the mageplaza.com license that is
 * available through the world-wide-web at this URL:
 * https://www.mageplaza.com/LICENSE.txt
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Mageplaza
 * @package     Mageplaza_Core
 * @copyright   Copyright (c) Mageplaza (https://www.mageplaza.com/)
 * @license     https://www.mageplaza.com/LICENSE.txt
 */

namespace Mageplaza\Core\Model;

use Exception;
use Magento\Framework\DataObject;
use Magento\Framework\HTTP\Adapter\CurlFactory;
use Mageplaza\Core\Helper\AbstractData;
use Laminas\Http\Request;

/**
 * Class Activate
 * @package Mageplaza\Core\Model
 */
class Activate extends DataObject
{
    /**
     * Localhost maybe not active via https
     * @inheritdoc
     */
    const MAGEPLAZA_ACTIVE_URL = 'https://dashboard.mageplaza.com/license/index/activate/?isAjax=true';

    /**
     * @var CurlFactory
     */
    protected $curlFactory;

    /**
     * Activate constructor.
     *
     * @param CurlFactory $curlFactory
     * @param array $data
     */
    public function __construct(
        CurlFactory $curlFactory,
        array $data = []
    ) {
        $this->curlFactory = $curlFactory;

        parent::__construct($data);
    }

    /**
     * @param array $params
     *
     * @return array
     */
    public function activate($params = [])
    {
        $result = ['success' => false];

        $curl = $this->curlFactory->create();
        $curl->write(
            Request::METHOD_POST,
            self::MAGEPLAZA_ACTIVE_URL,
            '1.1',
            [],
            http_build_query($params)
        );

        try {
            $resultCurl = $curl->read();
            if (empty($resultCurl)) {
                $result['message'] = __('Cannot connect to server. Please try again later.');
            } else {
                $responseBody = $this->extractBody($resultCurl);
                $result += AbstractData::jsonDecode($responseBody);
                if (isset($result['status']) && in_array($result['status'], [200, 201])) {
                    $result['success'] = true;
                }
            }
        } catch (Exception $e) {
            $result['message'] = $e->getMessage();
        }

        $curl->close();

        return $result;
    }

    /**
     * Extract the body from a response string
     *
     * @param string $response_str
     * @return string
     */
    public function extractBody($response_str)
    {
        $parts = preg_split('|(?:\r\n){2}|m', $response_str, 2);
        if (isset($parts[1])) {
            return $parts[1];
        }
        return '';
    }
}
`
