### ISSUE TITLE
Deprecated issue in Cron Job 

### ISSUE THREAD

**Issue by rajesh-xcube** [mageplaza/module-core#68]
Hi,

I am using Magento 2.4.6 with PHP 8.2, while checking cron logs getting below error.

Deprecated Functionality: Creation of dynamic property Mageplaza\Core\Cron\GetUpdate::$notifierPool is deprecated in /var/www/html/vendor/mageplaza/module-core/Cron/GetUpdate.php on line 88 Process went away.

**Comment by MoemenDarwish** [comment]
I have created a pull request to fix this issue

[](https://github.com/mageplaza/module-core/pull/69)

**Comment by hostep** [comment]
This can be closed, a fix was added in version 1.5.5, see: https://github.com/mageplaza/module-core/compare/v1.5.4...v1.5.5

@chuccv or @rajesh-xcube: could you close this issue? Thanks!
